### ISSUE TITLE
Example code throws error

### ISSUE THREAD

**Issue by hexiro** [offish/steam_community_market#5]
I ran
```
from steam_community_market import Market, AppID

market = Market("USD")

item = "AK-47 | Redline (Field Tested)"

market.get_lowest_price(item, AppID.CSGO)


market.get_volume(item, 730)
```
This threw:
```
Traceback (most recent call last):
  File "C:/Users/RealH/Desktop/Python Projects/HaveGenerator, SteamFunctions/test.py", line 7, in <module>
    market.get_lowest_price(item, AppID.CSGO)
  File "C:\Users\RealH\AppData\Local\Programs\Python\Python37\lib\site-packages\steam_community_market\market.py", line 178, in get_lowest_price
    if "lowest_price" in item:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by offish** [comment]
I can't seem to reproduce the error you're encountering, but I will look into this for a potential fix.
